SHOW PROCEDURE STATUS WHERE Name = 'CheckAvailabilityOverlap';

SHOW PROCEDURE STATUS WHERE Db = 'reservation_system';

SELECT ROUTINE_NAME, ROUTINE_DEFINITION, CREATED, LAST_ALTERED
FROM information_schema.ROUTINES
WHERE ROUTINE_SCHEMA = 'reservation_system' AND ROUTINE_TYPE = 'PROCEDURE';
